{% set name = "inetutils" %}
{% set version = "2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/inetutils/{{ name }}-{{ version }}.tar.gz
  sha256: fa043bbbc426eae1869070d2b6e29a98069615ac00681cdb92e20911d9292260

build:
  number: 0
  skip: true  # [win or osx]
  script: |
    ./configure \
      --prefix="$PREFIX" \
      --enable-ncurses
    make
    # TEST hostname.sh requires root permissions to sethostname
    # As not granted tests are disabled
    # make check
    make install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - ncurses
    - libxcrypt

test:
  commands:
    - test -f $PREFIX/bin/telnet  # [unix]
    - telnet --version

about:
  home: https://www.gnu.org/software/inetutils/
  summary: 'Inetutils is a collection of common network programs'
  description: |
    Inetutils is a collection of common network programs. It includes:
      - An inetd meta-server.
      - An ftp client and server.
      - A telnet client and server.
      - An rsh client and server.
      - An rlogin client and server.
      - A tftp client and server.
      - A talk client and server.
      - A syslogd daemon.
      - Network tools: ping, ping6, traceroute, whois.
      - Admin tools: hostname, dnsdomainname, ifconfig, logger
    And more...
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - chrros95
